---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: automerge

"on":
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Setup nodejs
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: lts/*

      - name: Generate token
        id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          app_id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.TOKEN_EXCHANGE_INSTALL }}
          private_key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permissions: >-
            {"contents": "write", "pull_requests": "write", "issues": "write"}

      - name: Fetch metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install deps
        run: sudo apt update && sudo apt install -y gh

      - name: Approve request
        run: gh pr review --approve "${{github.event.pull_request.html_url}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable automerge
        run: gh pr merge --rebase --auto "${{github.event.pull_request.html_url}}"
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}

...
